name = "CryptoDatasets"
uuid = "752056fd-441a-45a3-95f5-0eb545c140d0"
authors = ["g-gundam <gg@nowhere> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
